---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: go-server          
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: go-server        
  template:                      
    metadata:
      labels:                    
        app: go-server 
    spec:                        
      imagePullSecrets:
        - name: borenty-regcerd
      containers:
      - name: go-server
        image: ger-is-registry.caas.intel.com/crystal-ridge-tools/go-server:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "k"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready or not
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1  
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service 
spec:
  type: NodePort             
  ports:                         
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: go-server
